name: Laravel

on:
  push:
    branches: [ "main" ]
    paths-ignore:
      - '**/README.md'
  pull_request:
    branches: [ "main" ]
    paths-ignore:
      - '**/README.md'

jobs:
  laravel-tests:

    runs-on: ubuntu-latest

     # Setup the database with Docker container
    services:
      mysql:
        image: mysql:latest
        env:
          MYSQL_DATABASE: comicu
          MYSQL_ROOT_PASSWORD: 
          MYSQL_ALLOW_EMPTY_PASSWORD: yes
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
    
    steps:
    - uses: shivammathur/setup-php@15c43e89cdef867065b0213be354c2841860869e
      with:
        php-version: '8.2'
    - uses: actions/checkout@v3
    - name: Copy .env
      run: php -r "file_exists('.env') || copy('.env.example', '.env');"
    - name: Update composer
      run: composer update
    - name: Install Dependencies
      run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
    - name: Generate key
      run: php artisan key:generate
    - name: Debug
      run: |
        cat .env
        docker ps -a

    - name: Fresh migrate
      run: php artisan migrate:fresh --seed
    - name: Directory Permissions
      run: sudo chown -R runner:runner /home/runner/work/ | sudo chmod -R 777 /home/runner/work/
    - name: Execute tests (Unit and Feature tests) via PHPUnit
      env:
        DB_HOST: 127.0.0.1
        DB_DATABASE: comicu
        DB_CONNECTION: mysql
        DB_USERNAME: root
        DB_PASSWORD:
      run: vendor/bin/phpunit
